#!/bin/sh
# grep -v "#" ~/.scripts/unicode | dmenu -i -l 20 -fn Monospace-18 | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard
#
# notify-send "$(xclip -o -selection clipboard) copied to clipboard."

#pgrep -x dunst >/dev/null && notify-send "$(xclip -o -selection clipboard) copied to clipboard."

# selection=$(grep -v "#" ~/.scripts/unicode | dmenu -i -l 20 -fn Monospace-18)
selection=$(grep -v "#" ~/.scripts/unicode | rofi -dmenu -i)

# Exit if selection is empty
[ -z "$selection" ] && exit

echo -n "$selection" | awk '{print $1}' | tr -d '\n' | xclip -selection clipboard

notify-send "$(xclip -o -selection clipboard) copied to clipboard."

