#!/bin/bash

history_file="$HOME/.rofi_calc_history"

# Ask for input via rofi
expression=$(echo | rofi -dmenu -p "Calculator")

# If the input is not empty, calculate and save it
if [[ -n "$expression" ]]; then
    result=$(qalc -t "$expression")
    echo -e "$expression = $result" | rofi -dmenu -p "Result"
    echo "$(date +'%Y-%m-%d %H:%M:%S') : $expression = $result" >> "$history_file"
    echo -n $result | xclip -selection clipboard 
fi

